import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./componants/navbar";
import ContextProvider from "./context/Context";


const roboto = Roboto({
  weight: ['400', '700'], // Specify the weights you need
  subsets: ['latin'], // Specify the subsets you need
});
export const metadata: Metadata = {
  title: "MK System",
  description: "Generated by MK System",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body dir="rtl" className={roboto.className +' h-screen' }>
     <main className="flex flex-col w-screen h-screen"> <ContextProvider>
        <Navbar/>
        {children}</ContextProvider></main>
        </body>
    </html>
  );
}
